### ISSUE TITLE
Issue when registering

### ISSUE THREAD

**Issue by jansolecki** [monterail/montelearn#175]
<img width="489" alt="Zrzut ekranu 2020-06-30 o 09 45 23" src="https://user-images.githubusercontent.com/67631241/86106304-b0262b00-bac0-11ea-92fa-54352f5ba071.png">

When I tried to register and use a Google generated password (you know a lenghty complex one with !@#$#@) I got this error. When I changed to password to a simpler one it worked ;)

**Comment by mecies** [comment]
I believe the issue was that the authentication API (responsible for registration) was not awake, it took 10 seconds or so to wake up after your first request, and when you sent another request, it was already awake and able to process your registration. The issue shouldn't appear after we move the authentication API to a paid hosting plan. 👍

**Comment by mecies** [comment]
We upgraded to a paid Heroku plan so the issue should no longer occur.
